FROM python:3


RUN \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        vim \
        postgresql-client \
        libpq-dev \
        git && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir virtualenv

WORKDIR /usr/src/app

EXPOSE 8000

CMD ["/usr/src/env/bin/python", "/usr/src/app/manage.py", "runserver", "0.0.0.0:8000"]
